apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: bf96b13f-714c-4e41-8979-182eb6baf980
    workflow_id: 5fd19c9d-f480-43ba-93c9-0021e50df8eb
  name: custom-chaos-workflow-1619510958
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: coredns-pod-delete
        template: coredns-pod-delete
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - arguments: {}
    container:
      args:
      - kubectl apply -f /tmp/coredns-pod-delete.yaml -n {{workflow.parameters.adminModeNamespace}} |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: coredns-pod-delete
        path: /tmp/coredns-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Deletes coredns pod in kube-system namespace
            kind: ChaosExperiment
            metadata:
              name: coredns-pod-delete
              labels:
                name: coredns-pod-delete
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 1.13.3
            spec:
              definition:
                permissions:
                  - apiGroups:
                      - ""
                      - batch
                      - litmuschaos.io
                    resources:
                      - services
                      - jobs
                      - pods
                      - pods/log
                      - events
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - get
                      - list
                      - patch
                      - create
                      - update
                      - delete
                image: litmuschaos/ansible-runner:1.13.3
                imagePullPolicy: Always
                args:
                  - -c
                  - ansible-playbook
                    ./experiments/coredns/pod_delete/pod_delete_ansible_logic.yml -i
                    /etc/ansible/hosts -vv; exit 0
                command:
                  - /bin/bash
                env:
                  - name: ANSIBLE_STDOUT_CALLBACK
                    value: default
                  - name: TOTAL_CHAOS_DURATION
                    value: "15"
                  - name: KILL_COUNT
                    value: ""
                  - name: FORCE
                    value: "true"
                  - name: CHAOS_INTERVAL
                    value: "5"
                  - name: LIB
                    value: litmus
                  - name: LIB_IMAGE
                    value: litmuschaos/pod-delete-helper:latest
                labels:
                  name: coredns-pod-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 1.13.3
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-coredns-pod-delete.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: coredns-pod-delete
        path: /tmp/chaosengine-coredns-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: coredns-pod-delete-1619510955
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-dns
                appkind: deployment
              annotationCheck: "false"
              engineState: active
              auxiliaryAppInfo: ""
              chaosServiceAccount: litmus-admin
              jobCleanUpPolicy: delete
              experiments:
                - name: coredns-pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: CHAOS_NAMESPACE
                          value: kube-system
    metadata:
      labels:
        weight: "10"
    name: coredns-pod-delete
    outputs: {}
  - arguments: {}
    container:
      args:
      - kubectl delete chaosengine coredns-pod-delete-1619510955 -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
